### ISSUE TITLE
Unknown pin chip name 'virtual_pin'

### ISSUE THREAD

**Issue by EonPrintCrafter** [K1-Klipper/installer_script_k1_and_max#10]
Unknown pin chip name 'virtual_pin'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

Got this after doing this install on a k1 thats rooted and helped to preform with the helper script. yet now everything is broken and it even gives me a filament fault. Great job man, really nice.

**Comment by sbtoonz** [comment]
This has nothing to do with my installer this is from Guiloze installer

**Comment by sbtoonz** [comment]
https://github.com/K1-Klipper/installer_script_k1_and_max/commit/7504b2cb708594f3e36af987bc73d4279d6cbfc3
