### ISSUE TITLE
K1C clr_noz_quick is not valid

### ISSUE THREAD

**Issue by xGreenPandax** [K1-Klipper/installer_script_k1_and_max#7]
Original printer.cfg in K1C has this lines:
```
clr_noz_quick: true
clr_quick_high:0.7
clr_xy_quick_spd:100
clr_quick_times:10
clr_quick_react_dis:5
```
But looks like _clr_noz_quick_ was built in param in origin custom mcu firmware.

And now I got Klipper error: Option 'clr_noz_quick' is not valid in section 'prtouch_v2'

**Comment by xGreenPandax** [comment]
Btw there is additional problem
![image](https://github.com/K1-Klipper/installer_script_k1_and_max/assets/18736714/4f8dca94-7fc5-4d7f-8e8f-c37f885b5475)

**Comment by xGreenPandax** [comment]
Btw there is problem with display now. Printer works well, but on the display there is no data of sensors.
![image](https://github.com/K1-Klipper/installer_script_k1_and_max/assets/18736714/ebfc5187-1033-48aa-b7da-2152ffcf600c)

**Comment by sbtoonz** [comment]
This does not support K1C,

Screen issue is known use guppy screen
