### ISSUE TITLE
Add starting conditions

### ISSUE THREAD

**Issue by Chinstrap777** [K1-Klipper/installer_script_k1_and_max#9]
I've been having issues trying to get this to work on my K1 Max. Every time I run the script, my printer display goes black after the splash screen, and on mainsail I get an error that basically states that there's a mismatch between the MCUs' firmwares.  If there's a set of conditions that are needed in order to run the script properly, could you add them to the page? Something like "Prior to running this script ensure that..."

**Comment by Chinstrap777** [comment]
![IMG_5907](https://github.com/K1-Klipper/installer_script_k1_and_max/assets/147956858/7b8c5783-1a4b-4f46-a96c-cb4da8e942c5)

**Comment by sbtoonz** [comment]
https://github.com/K1-Klipper/installer_script_k1_and_max/blob/main/installer.sh#L19

This line of code would sed out the config stuff that calls the rpi MCU

I can also compile an updated linux-host process I suppose as well
